#!/usr/bin/env python2
import sys
import os
import datetime

from decorator import decorator

from sqlalchemy import Column, Integer, String, ForeignKey, DateTime, Boolean, create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

# {{{ Help
"""
Usage Examples
--------------

ani new anime: clannad -- Adds a series with a season
ani watch: clannad -- Increments episode count, adds a season if last ep
ani watch +3: clannad -- Watch 3 episodes on clannad's current season
ani rate 8: clannad -- Set score
ani drop: clannad -- Set dropped
ani undrop: clannad -- Set undropped
ani season add: clannad -- Add a new season
ani season add 8: clannad -- Add season with number 8
ani season remove: clannad -- Remove current season
ani season remove 1: clannad -- Remove season 1
ani season active 4: clannad -- Set active season
ani season length 4 24: clannad -- Set season 4 length 24
ani length 24: clannad -- Set current season length 24
"""

HELPTEXT = """
Usage: %s [COMMAND] [ARGS...]: [SELECTOR]
Manage list of watched anime and television series.

Database:
    By default anigrate uses an sqlite database in $HOME/.anigrate/db,
    see the example anigraterc for all the other possibilities.

Commands:
    initdb
        Initialise the database with all the necessary tables.

    add [category]: (selector)
        Add a new series entry with name specified by (selector).
        Optionally you can enter a category to mark it as.

    remove: (selector)
        Completely remove any series that match (selector).

    rate <score>: (selector)
        Rate all series matched by (selector) with <score>.

    [un]drop: (selector)
        Mark all series matched by (selector) as dropped or not dropped.

    length <length>: [selector]
        Set the active season's length in episodes.

    watch [num]: (selector)
        Change the episodes watched count. Without [num] specified it will be
        incremented by one. Using specifiers like "+3" or "-2" you can increment
        or decrement the watched count by that number. Specifying an absolute
        number will watch up to that episode or remove everything from that
        episode on. Watch always uses the currently active season.

    season add [num]: [selector]
        Add a new season, if num is specified the season number is set to that, 
        otherwise it will default to one more than the previous season.

    season remove [num]: [selector]
        Remove the season with number [num] from a series. If num is not
        specified the currently active season will be removed.

    season length <season> <length>: [selector]
        Set a season's length in episodes.

    season active <num>: [selector]
        Set season with number <num> as the active season. Can be a relative 
        offset like +1 or -2.

"""
# }}}

# {{{ Constants
CONF_DIR = os.getenv("HOME")+"/.anigrate"
DB_LOCATION = CONF_DIR+"/db"

# }}}

# {{{ Models
Base = declarative_base()
Session = sessionmaker()

class Series(Base):
    """An entire series."""
    __tablename__ = "series"
    id = Column(Integer, primary_key=True)
    rating = Column(Integer, default=0)
    title = Column(String(255))

    current = Column(Integer)
    ctime = Column(DateTime)
    mtime = Column(DateTime)
    dropped = Column(Boolean, default=False)
    category = Column(String(255), default="")
    duration = Column(Integer, default=22)

    def getseason(self, session, num=None):
        """Retrieve a season based on its number."""
        return session.query(Season).filter(
            Season.series == self.id
        ).filter(
            Season.num == (self.current if num==None else num)
        ).first()

class Season(Base):
    """One season of a series."""
    __tablename__ = "seasons"
    id = Column(Integer, primary_key=True)
    num = Column(Integer)

    series = Column(ForeignKey("series.id"))
    episode_total = Column(Integer, default=0)
    current_watched = Column(Integer, default=0)

class Watched(Base):
    """A 'watched episodes' event attached to a season."""
    __tablename__ = "watched"
    id = Column(Integer, primary_key=True)

    season = Column(ForeignKey("seasons.id"))

    startep = Column(Integer)
    finishep = Column(Integer)
# }}}

# {{{ Utility functions
commands = {}

def command(name=None, cmds=None):
    """Register a function as a command."""
    def cmd(func):
        # Get command dict
        if cmds == None:
            global commands
            cm = commands
        else:
            cm = cmds

        cm[(name or func.__name__)] = func
        return func

    return cmd

def getcommand(name, cmds=None):
    """Get a command by name."""
    # Get command dict
    if cmds == None:
        global commands
        cmd = commands
    else:
        cmd = cmds

    # Exact match
    if name in cmd:
        return cmd[name]

    # Prefix match
    candidate = filter(lambda x: x.startswith(name), cmd.keys())

    if len(candidate) == 1:
        return cmd[candidate[0]]
    elif candidate:
        return candidate
    else:
        return None

def dbbind():
    """Bind the sqlalchemy database engine and return the session."""
    if not os.access(CONF_DIR, os.F_OK):
        os.mkdir(CONF_DIR)

    engine = create_engine('sqlite:///'+DB_LOCATION)
    Base.metadata.bind = engine
    Session.configure(bind=engine)

    if not os.access(DB_LOCATION, os.F_OK):
        initdb(session=Session())

    return Session()

def getselection(session, selector):
    """Get all anime matching a selector"""
    return session.query(Series).filter(Series.title.startswith(selector)).all()

# }}}

# {{{ Commands
# {{{ initdb
@command()
def initdb(arg=None, selector=None, session=None):
    """Initialise the database for use."""
    if not session:
        dbbind()
    Base.metadata.create_all()
# }}}

# {{{ add
@command()
def add(arg, selector):
    if not selector:
        print("Error: selector required.")
        return

    # Bind database
    session = dbbind()

    # Don't create if one already exists
    if session.query(Series).filter(Series.title == selector).all():
        print("Error: A series with this name already exists...")
        return

    # Create a new series
    series = Series(title=selector, current=1)
    series.ctime = datetime.datetime.now()
    series.mtime = datetime.datetime.now()

    session.add(series)
    session.commit()

    ## Category
    if arg:
        series.category = arg[0]

    ## First season
    season = Season(num=1)
    season.series = series.id

    print("Adding: %s..." % series.title)
    session.add(season)
    session.commit()
# }}}

# {{{ remove
@command()
def remove(arg, selector):
    """Remove a series in totality."""
    if not selector:
        return "Error: selector required."

    # Bind database
    session = dbbind()
    selection = getselection(session, selector)

    if not selection:
        return "Error: no series match selector."

    for sel in selection:
        print("Removing: %s..." % sel.title)

        for season in session.query(Season).filter(Season.series == sel.id).all():
            session.query(Watched).filter(Watched.season == season.id).delete(False)
            session.delete(season)

        session.delete(sel)

    session.commit()
# }}}

# {{{ rate
@command()
def rate(arg, selector):
    """Set the rating/score for a series."""
    if not selector:
        return "Error: selector required."

    if not arg:
        return "Error: rating required."

    try:
        score = int(arg[0])
    except:
        return "Error: rating is not a valid number."

    # Bind database
    session = dbbind()
    selection = getselection(session, selector)

    for sel in selection:
        print("Rating %d: %s..." %(score, sel.title))
        sel.rating = score

    session.commit()
# }}}
    
# {{{ [un]drop
@command()
def drop(arg, selector):
    """Drop a series."""
    if not selector:
        return "Error: selector required."

    # Bind database
    session = dbbind()
    selection = getselection(session, selector)


    if not selection:
        return "Error: no series match selector."

    for sel in selection:
        print("Dropping: %s..." % sel.title)
        sel.dropped = True

    session.commit()

@command()
def undrop(arg, selector):
    """Undrop a series."""
    if not selector:
        return "Error: selector required."

    # Bind database
    session = dbbind()
    selection = getselection(session, selector)

    for sel in selection:
        print("Undropping: %s..." % sel.title)
        sel.dropped = False

    session.commit()
# }}}

# {{{ length
@command()
def length(arg, selector):
    """Set the current season's length for a series."""
    if not selector:
        return "Error: selector required."

    if not arg:
        return "Error: length required."

    try:
        length = int(arg[0])
    except:
        return "Error: length is not a valid number."

    # Bind database
    session = dbbind()
    selection = getselection(session, selector)

    for sel in selection:
        season = sel.getseason(session)
        season.episode_total = length

        print("Setting season %d length to %d: %s..."%
                (season.num, length, sel.title))

    session.commit()
# }}}

# {{{ season
global seasoncmd
seasoncmd = {}

@command()
def season(arg, selector):
    """Run a season command"""
    if not arg:
        return "Error: season command required."

    global seasoncmd
    cmd = getcommand(arg[0], cmds=seasoncmd)

    if callable(cmd):
        return cmd(arg[1:], selector)
    elif cmd:
        print("Error: ambiguous season command, available:")
        print("\n".join(("  %s season "+x)%sys.argv[0] for x in cmd))
        exit(1)
    else:
        return "Error: Invalid Season Command: %s" % arg[0]

# {{{ active
@command(cmds=seasoncmd)
def active(arg, selector):
    """Set the rating/score for a series."""
    if not selector:
        return "Error: selector required."

    # Bind database
    session = dbbind()
    selection = getselection(session, selector)

    # Get number
    if arg:
        try:
            rel = arg[0][0] in ('+', '-')
            num = int(arg[0])
        except:
            return "Error: season number is not a valid number."
    else:
        return "Error: season number required."

    if not selection:
        return "Error: no series match selector."

    for sel in selection:
        sn = sel.current+num if rel else num

        if sn < 1:
            print("Error: season number for series %s too low (%d)."
                    % (sel.title, sn))
            continue

        if not sel.getseason(session, sn):
            print("Error: season %d for series %s doesn't exist."
                    % (sn, sel.title))
            continue

        print("Activating season %d: %s..." % (sn, sel.title))
        sel.current = sn

    session.commit()
# }}}

# {{{ add
@command(cmds=seasoncmd)
def add(arg, selector):
    """Set the rating/score for a series."""
    if not selector:
        return "Error: selector required."

    # Bind database
    session = dbbind()
    selection = getselection(session, selector)

    # Get number
    if arg:
        try:
            num = int(arg[0])
        except:
            return "Error: season number is not a valid number."
    else:
        num = None

    if not selection:
        return "Error: no series match selector."

    for sel in selection:
        sn = sel.current+1 if num==None else num

        if sn < 1:
            print("Error: season number for series %s too low (%d)."
                    % (sel.title, sn))
            continue

        if sel.getseason(session, sn):
            print("Error: season %d for series %s already exists."
                    % (sn, sel.title))
            continue

        season = Season()
        season.series = sel.id
        season.num = sn
        sel.current = season.num

        print("Adding season %d: %s..." % (sn, sel.title))
        session.add(season)

    session.commit()
# }}}

# {{{ remove
@command(cmds=seasoncmd)
def remove(arg, selector):
    """Remove a season from a series."""
    if not selector:
        return "Error: selector required."

    # Bind database
    session = dbbind()
    selection = getselection(session, selector)

    # Get number
    if arg:
        try:
            num = int(arg[0])
        except:
            return "Error: season number is not a valid number."
    else:
        num = None

    if not selection:
        return "Error: no series match selector."

    for sel in selection:
        sn = sel.current if num==None else num

        if sn < 1:
            print("Error: season number for series %s too low (%d)."
                    % (sel.title, sn))
            continue

        # Find season
        season = sel.getseason(session, sn)

        # Check for existence
        if not season:
            print("Error: season %d for series %s doesn't exist."
                    % (sn, sel.title))
            continue

        # Delete watched
        session.query(Watched).filter(Watched.season == season.id).delete(False)

        # Delete
        print("Removing season %d: %s..." % (sn, sel.title))
        session.delete(season)

        if sel.current == sn:
            # Get new season number
            sn -= 1
            while sn > 0 and not sel.getseason(session, sn):
                sn -= 1
            sel.current = sn


    session.commit()
# }}}

# {{{ length
@command(cmds=seasoncmd)
def length(arg, selector):
    """Set the current season's length for a series."""
    if not selector:
        return "Error: selector required."

    if len(arg) < 2:
        return "Error: insufficient arguments."

    try:
        num = int(arg[0])
    except:
        return "Error: season number is not a valid number."

    try:
        length = int(arg[0])
    except:
        return "Error: length is not a valid number."

    # Bind database
    session = dbbind()
    selection = getselection(session, selector)

    for sel in selection:
        season = sel.getseason(session, num)
        season.episode_total = length

        print("Setting season %d length to %d: %s..."%
                (num, length, sel.title))

    session.commit()
# }}}

# }}}

# }}}

# {{{ Main function
def main():
    # Retrieve arguments
    arg = sys.argv[1:]

    # Intercept help
    if not arg or arg[0] in ("help", "--help", "-h"):
        print(HELPTEXT%sys.argv[0])
        return

    # Get selector and arguments
    ## Check if there exists a selector
    if filter(lambda x: x.endswith(":"), arg):
        selector = []

        # Build selector
        for i,x in enumerate(reversed(arg[1:])):
            if x.endswith(":"):
                break
            else:
                selector.insert(0, x)
                arg.remove(x)

        selector = " ".join(selector)

        # Remove colon
        arg[-1] = arg[-1][:-1]
    else:
        selector=None

    # Call the command
    cmd = getcommand(arg[0])

    if callable(cmd):
        res = cmd(arg[1:], selector)

        if res:
            # An error occured
            print(res)
            exit(1)
    elif cmd:
        print("Error: ambiguous command, available:")
        print("\n".join(("  %s "+x)%sys.argv[0] for x in cmd))
        exit(1)
    else:
        print("Error: Invalid Command: %s" % arg[0])
        print(HELPTEXT%sys.argv[0])
        exit(1)
# }}}

# Call main function
if __name__ == '__main__':
    main()
# vim: set fdm=marker :
